# Generated by Django 3.2.5 on 2021-07-26 17:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0002_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_data',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='followers',
            unique_together={('user', 'follower')},
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('author', 'title')},
        ),
    ]
